const lead = [
  {
    index: 0,
    name: 'Annual_Revenue',
    label: 'Annual Revenue',
    type: 'currency',
    editable: true,
    types: 'double',
  },
  {
    index: 1,
    name: 'City',
    label: 'City',
    type: 'text',
    editable: true,
    types: 'string',
  },
  {
    index: 2,
    name: 'Company',
    label: 'Company',
    type: 'text',
    editable: true,
    types: 'string',
  },
  {
    index: 3,
    name: 'Converted_Account',
    label: 'Converted Account',
    type: 'lookup',
    editable: false,
    types: 'jsonobject',
  },
  {
    index: 4,
    name: 'Converted_Contact',
    label: 'Converted Contact',
    type: 'lookup',
    editable: false,
    types: 'jsonobject',
  },
  {
    index: 5,
    name: 'Converted_Deal',
    label: 'Converted Deal',
    type: 'lookup',
    editable: false,
    types: 'jsonobject',
  },
  {
    index: 6,
    name: 'Country',
    label: 'Country',
    type: 'text',
    editable: true,
    types: 'string',
  },
  {
    index: 7,
    name: 'Created_By',
    label: 'Created By',
    type: 'ownerlookup',
    editable: true,
    types: 'jsonobject',
  },
  {
    index: 8,
    name: 'Created_Time',
    label: 'Created Time',
    type: 'datetime',
    editable: false,
    types: 'string',
  },
  {
    index: 9,
    name: 'Description',
    label: 'Description',
    type: 'textarea',
    editable: true,
    types: 'string',
  },
  {
    index: 10,
    name: 'Designation',
    label: 'Designation',
    type: 'text',
    editable: true,
    types: 'string',
  },
  {
    index: 11,
    name: 'Email',
    label: 'Email',
    type: 'email',
    editable: true,
    types: 'string',
  },
  {
    index: 12,
    name: 'Email_Opt_Out',
    label: 'Email Opt Out',
    type: 'boolean',
    editable: true,
    types: 'boolean',
  },
  {
    index: 13,
    name: 'Enrich_Status__s',
    label: 'Enrich Status',
    type: 'picklist',
    editable: true,
    types: 'string',
  },
  {
    index: 14,
    name: 'Fax',
    label: 'Fax',
    type: 'text',
    editable: true,
    types: 'string',
  },
  {
    index: 15,
    name: 'First_Name',
    label: 'First Name',
    type: 'text',
    editable: true,
    types: 'string',
  },
  {
    index: 16,
    name: 'Full_Name',
    label: 'Full Name',
    type: 'text',
    editable: false,
    types: 'string',
  },
  {
    index: 17,
    name: 'Industry',
    label: 'Industry',
    type: 'picklist',
    editable: true,
    types: 'string',
  },
  {
    index: 18,
    name: 'Last_Activity_Time',
    label: 'Last Activity Time',
    type: 'datetime',
    editable: false,
    types: 'string',
  },
  {
    index: 19,
    name: 'Last_Enriched_Time__s',
    label: 'Last Enriched Time',
    type: 'datetime',
    editable: true,
    types: 'string',
  },
  {
    index: 20,
    name: 'Last_Name',
    label: 'Last Name',
    type: 'text',
    editable: true,
    types: 'string',
  },
  {
    index: 21,
    name: 'Lead_Conversion_Time',
    label: 'Lead Conversion Time',
    type: 'integer',
    editable: false,
    types: 'integer',
  },
  {
    index: 22,
    name: 'Owner',
    label: 'Lead Owner',
    type: 'ownerlookup',
    editable: true,
    types: 'jsonobject',
  },
  {
    index: 23,
    name: 'Lead_Source',
    label: 'Lead Source',
    type: 'picklist',
    editable: true,
    types: 'string',
  },
  {
    index: 24,
    name: 'Lead_Status',
    label: 'Lead Status',
    type: 'picklist',
    editable: true,
    types: 'string',
  },
  {
    index: 25,
    name: 'Mobile',
    label: 'Mobile',
    type: 'phone',
    editable: true,
    types: 'string',
  },
  {
    index: 26,
    name: 'Modified_By',
    label: 'Modified By',
    type: 'ownerlookup',
    editable: true,
    types: 'jsonobject',
  },
  {
    index: 27,
    name: 'Modified_Time',
    label: 'Modified Time',
    type: 'datetime',
    editable: false,
    types: 'string',
  },
  {
    index: 28,
    name: 'No_of_Employees',
    label: 'No of Employees',
    type: 'integer',
    editable: true,
    types: 'integer',
  },
  {
    index: 29,
    name: 'Phone',
    label: 'Phone',
    type: 'phone',
    editable: true,
    types: 'string',
  },
  {
    index: 30,
    name: 'Rating',
    label: 'Rating',
    type: 'picklist',
    editable: true,
    types: 'string',
  },
  {
    index: 31,
    name: 'Record_Image',
    label: 'Record Image',
    type: 'profileimage',
    editable: true,
    types: 'string',
  },
  {
    index: 32,
    name: 'Salutation',
    label: 'Salutation',
    type: 'picklist',
    editable: false,
    types: 'string',
  },
  {
    index: 33,
    name: 'Secondary_Email',
    label: 'Secondary Email',
    type: 'email',
    editable: true,
    types: 'string',
  },
  {
    index: 34,
    name: 'Skype_ID',
    label: 'Skype ID',
    type: 'text',
    editable: true,
    types: 'string',
  },
  {
    index: 35,
    name: 'State',
    label: 'State',
    type: 'text',
    editable: true,
    types: 'string',
  },
  {
    index: 36,
    name: 'Street',
    label: 'Street',
    type: 'text',
    editable: true,
    types: 'string',
  },
  {
    index: 37,
    name: 'Tag',
    label: 'Tag',
    type: 'text',
    editable: false,
    types: 'jsonarray',
  },
  {
    index: 38,
    name: 'Twitter',
    label: 'Twitter',
    type: 'text',
    editable: true,
    types: 'string',
  },
  {
    index: 39,
    name: 'Unsubscribed_Mode',
    label: 'Unsubscribed Mode',
    type: 'picklist',
    editable: false,
    types: 'string',
  },
  {
    index: 40,
    name: 'Unsubscribed_Time',
    label: 'Unsubscribed Time',
    type: 'datetime',
    editable: false,
    types: 'string',
  },
  {
    index: 41,
    name: 'Website',
    label: 'Website',
    type: 'website',
    editable: true,
    types: 'string',
  },
  {
    index: 42,
    name: 'Zip_Code',
    label: 'Zip Code',
    type: 'text',
    editable: true,
    types: 'string',
  },
];

const contact = [
  {
    index: 0,
    name: 'Account_Name',
    label: 'Account Name',
    type: 'lookup',
    editable: true,
    types: 'jsonobject',
  },
  {
    index: 1,
    name: 'Assistant',
    label: 'Assistant',
    type: 'text',
    editable: true,
    types: 'string',
  },
  {
    index: 2,
    name: 'Asst_Phone',
    label: 'Asst Phone',
    type: 'phone',
    editable: true,
    types: 'string',
  },
  {
    index: 3,
    name: 'Owner',
    label: 'Contact Owner',
    type: 'ownerlookup',
    editable: true,
    types: 'jsonobject',
  },
  {
    index: 4,
    name: 'Created_By',
    label: 'Created By',
    type: 'ownerlookup',
    editable: true,
    types: 'jsonobject',
  },
  {
    index: 5,
    name: 'Created_Time',
    label: 'Created Time',
    type: 'datetime',
    editable: false,
    types: 'string',
  },
  {
    index: 6,
    name: 'Date_of_Birth',
    label: 'Date of Birth',
    type: 'date',
    editable: true,
    types: 'string',
  },
  {
    index: 7,
    name: 'Department',
    label: 'Department',
    type: 'text',
    editable: true,
    types: 'string',
  },
  {
    index: 8,
    name: 'Description',
    label: 'Description',
    type: 'textarea',
    editable: true,
    types: 'string',
  },
  {
    index: 9,
    name: 'Email',
    label: 'Email',
    type: 'email',
    editable: true,
    types: 'string',
  },
  {
    index: 10,
    name: 'Email_Opt_Out',
    label: 'Email Opt Out',
    type: 'boolean',
    editable: true,
    types: 'boolean',
  },
  {
    index: 11,
    name: 'Enrich_Status__s',
    label: 'Enrich Status',
    type: 'picklist',
    editable: true,
    types: 'string',
  },
  {
    index: 12,
    name: 'Fax',
    label: 'Fax',
    type: 'text',
    editable: true,
    types: 'string',
  },
  {
    index: 13,
    name: 'First_Name',
    label: 'First Name',
    type: 'text',
    editable: true,
    types: 'string',
  },
  {
    index: 14,
    name: 'Full_Name',
    label: 'Full Name',
    type: 'text',
    editable: false,
    types: 'string',
  },
  {
    index: 15,
    name: 'Home_Phone',
    label: 'Home Phone',
    type: 'phone',
    editable: true,
    types: 'string',
  },
  {
    index: 16,
    name: 'Last_Activity_Time',
    label: 'Last Activity Time',
    type: 'datetime',
    editable: false,
    types: 'string',
  },
  {
    index: 17,
    name: 'Last_Enriched_Time__s',
    label: 'Last Enriched Time',
    type: 'datetime',
    editable: true,
    types: 'string',
  },
  {
    index: 18,
    name: 'Last_Name',
    label: 'Last Name',
    type: 'text',
    editable: true,
    types: 'string',
  },
  {
    index: 19,
    name: 'Lead_Source',
    label: 'Lead Source',
    type: 'picklist',
    editable: true,
    types: 'string',
  },
  {
    index: 20,
    name: 'Mailing_City',
    label: 'Mailing City',
    type: 'text',
    editable: true,
    types: 'string',
  },
  {
    index: 21,
    name: 'Mailing_Country',
    label: 'Mailing Country',
    type: 'text',
    editable: true,
    types: 'string',
  },
  {
    index: 22,
    name: 'Mailing_State',
    label: 'Mailing State',
    type: 'text',
    editable: true,
    types: 'string',
  },
  {
    index: 23,
    name: 'Mailing_Street',
    label: 'Mailing Street',
    type: 'text',
    editable: true,
    types: 'string',
  },
  {
    index: 24,
    name: 'Mailing_Zip',
    label: 'Mailing Zip',
    type: 'text',
    editable: true,
    types: 'string',
  },
  {
    index: 25,
    name: 'Mobile',
    label: 'Mobile',
    type: 'phone',
    editable: true,
    types: 'string',
  },
  {
    index: 26,
    name: 'Modified_By',
    label: 'Modified By',
    type: 'ownerlookup',
    editable: true,
    types: 'jsonobject',
  },
  {
    index: 27,
    name: 'Modified_Time',
    label: 'Modified Time',
    type: 'datetime',
    editable: false,
    types: 'string',
  },
  {
    index: 28,
    name: 'Other_City',
    label: 'Other City',
    type: 'text',
    editable: true,
    types: 'string',
  },
  {
    index: 29,
    name: 'Other_Country',
    label: 'Other Country',
    type: 'text',
    editable: true,
    types: 'string',
  },
  {
    index: 30,
    name: 'Other_Phone',
    label: 'Other Phone',
    type: 'phone',
    editable: true,
    types: 'string',
  },
  {
    index: 31,
    name: 'Other_State',
    label: 'Other State',
    type: 'text',
    editable: true,
    types: 'string',
  },
  {
    index: 32,
    name: 'Other_Street',
    label: 'Other Street',
    type: 'text',
    editable: true,
    types: 'string',
  },
  {
    index: 33,
    name: 'Other_Zip',
    label: 'Other Zip',
    type: 'text',
    editable: true,
    types: 'string',
  },
  {
    index: 34,
    name: 'Phone',
    label: 'Phone',
    type: 'phone',
    editable: true,
    types: 'string',
  },
  {
    index: 35,
    name: 'Record_Image',
    label: 'Record Image',
    type: 'profileimage',
    editable: true,
    types: 'string',
  },
  {
    index: 36,
    name: 'Reporting_To',
    label: 'Reporting To',
    type: 'lookup',
    editable: true,
    types: 'jsonobject',
  },
  {
    index: 37,
    name: 'Salutation',
    label: 'Salutation',
    type: 'picklist',
    editable: false,
    types: 'string',
  },
  {
    index: 38,
    name: 'Secondary_Email',
    label: 'Secondary Email',
    type: 'email',
    editable: true,
    types: 'string',
  },
  {
    index: 39,
    name: 'Skype_ID',
    label: 'Skype ID',
    type: 'text',
    editable: true,
    types: 'string',
  },
  {
    index: 40,
    name: 'Tag',
    label: 'Tag',
    type: 'text',
    editable: false,
    types: 'jsonarray',
  },
  {
    index: 41,
    name: 'Title',
    label: 'Title',
    type: 'text',
    editable: true,
    types: 'string',
  },
  {
    index: 42,
    name: 'Twitter',
    label: 'Twitter',
    type: 'text',
    editable: true,
    types: 'string',
  },
  {
    index: 43,
    name: 'Unsubscribed_Mode',
    label: 'Unsubscribed Mode',
    type: 'picklist',
    editable: false,
    types: 'string',
  },
  {
    index: 44,
    name: 'Unsubscribed_Time',
    label: 'Unsubscribed Time',
    type: 'datetime',
    editable: false,
    types: 'string',
  },
  {
    index: 45,
    name: 'Vendor_Name',
    label: 'Vendor Name',
    type: 'lookup',
    editable: true,
    types: 'jsonobject',
  },
];

// date, datetime, number, currency
export const date = {
  '=': '=',
  '!=': '!=',
  '>=': '>=',
  '>': '>',
  '<': '<',
  '<=': '<=',
  in: 'in',
  notIn: 'not in',
  isNull: 'is null',
  isNotNull: 'is not null',
  between: 'between',
  notBetween: 'not between',
};

// text, picklist

export const text = {
  '=': '=',
  '!=': '!=',
  like: 'like',
  notLike: 'not like',
  in: 'in',
  notIn: 'not in',
  isNull: 'is null',
  isNotNull: 'is not null',
};

// lookup

export const lookup = {
  '=': '=',
  '!=': '!=',
  in: 'in',
  notIn: 'not in',
  isNull: 'is null',
  isNotNull: 'is not null',
};

export const boolean = {
  '=': '=',
};

export const supportedOperator = [
  'boolean',
  'lookup',
  'text',
  'picklist',
  'date',
  'datetime',
  'number',
  'currency',
];
export { lead, contact };
